trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'cicdjava'

stages:
  - stage: Build
    displayName: 'Build Java App'
    jobs:
      - job: MavenBuild
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'

          - publish: target/*.jar
            artifact: drop

  - stage: Docker
    displayName: 'Build and Push Docker Image'
    dependsOn: Build
    jobs:
      - job: DockerBuildPush
        steps:
          - task: Docker@2
            displayName: 'Build and Push Image to ACR'
            inputs:
              command: 'buildAndPush'
              repository: '$(imageName)'
              dockerfile: 'Dockerfile'
              containerRegistry: 'MyACRConnection'
              tags: |
                $(Build.BuildId)
