trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'cicdjava'

stages:
  # ---------------------------
  # Stage 1: Build Java JAR
  # ---------------------------
  - stage: Build
    displayName: 'Build Java App'
    jobs:
      - job: MavenBuild
        displayName: 'Maven Build'
        steps:
          # Step 1: Checkout Code
          - checkout: self

          # Step 2: Build with Maven
          - task: Maven@3
            displayName: 'Build with Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'

          # Step 3: Publish JAR Artifact
          - publish: target/*.jar
            artifact: drop

  # ---------------------------
  # Stage 2: Build & Push Docker Image
  # ---------------------------
  - stage: Docker
    displayName: 'Build and Push Docker Image'
    dependsOn: Build
    jobs:
      - job: DockerBuildPush
        displayName: 'Docker Build & Push'
        steps:
          - checkout: self

          - task: Docker@2
            displayName: 'Build and Push Image to ACR'
            inputs:
              command: 'buildAndPush'
              containerRegistry: 'My-Azure-Connection'
              repository: 'cicdjava'
              dockerfile: 'Dockerfile'
              tags: |
                $(Build.BuildId)
